[package]
name = "dist_tx"
version = "0.1.0"
authors = ["emabee <meinolf.block@sap.com>"]
description = "A rust language binding for XA Distributed Transactions"
keywords = ["distributed", "transactions", "XA"]
license = "MIT/Apache-2.0"
repository = "https://github.com/emabee/rust-dist_tx"
documentation = "https://docs.rs/dist_tx/"

[dependencies]
bitflags = "1.0"
byteorder = "1.1"
log = "0.4"