[package]
name = "dist_tx_shared"
version = "0.3.0-unpublished"
authors = ["emabee <meinolf.block@sap.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.0"
byteorder = "1.3"
thiserror = "1.0"
